# Generated by Django 5.2.17 on 2026-09-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Street address or highway exit', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail price per gallon in USD', max_digits=7)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
            ],
            options={
                'ordering': ['state', 'city', 'retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='route_optim_latitud_35e793_idx'), models.Index(fields=['state', 'retail_price'], name='route_optim_state_cef970_idx')],
            },
        ),
    ]
